# Generated by Django 2.2.12 on 2020-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0003_auto_20200825_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='github_profile',
            field=models.URLField(default='https://placeholder'),
            preserve_default=False,
        ),
    ]
