# Generated by Django 2.2.12 on 2020-08-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0004_cv_github_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='github_profile',
            field=models.URLField(default='https://placeholder'),
        ),
    ]
