# Generated by Django 2.2.12 on 2020-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0005_auto_20200826_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='linkedin_profile',
            field=models.URLField(default='https://placeholder'),
        ),
    ]
