# Generated by Django 2.2.12 on 2020-08-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0008_auto_20200826_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecv.CV')),
            ],
        ),
    ]
