# Generated by Django 2.2.12 on 2020-08-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0009_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
