# Generated by Django 2.2.12 on 2020-08-27 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0010_qualification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='start_date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
