# Generated by Django 2.2.12 on 2020-08-27 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0011_qualification_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='end_date',
            field=models.DateField(default=datetime.date(1970, 1, 2)),
        ),
    ]
