# Generated by Django 2.2.12 on 2020-08-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0014_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='linked_cv',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='onlinecv.CV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
