# Generated by Django 2.2.12 on 2020-08-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0015_auto_20200828_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='title',
            new_name='job_title',
        ),
    ]
