# Generated by Django 2.2.12 on 2020-08-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0018_auto_20200828_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
