# Generated by Django 2.2.12 on 2020-08-29 11:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0019_auto_20200828_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='', max_length=200)),
                ('start_date', models.DateField(default=datetime.date(1970, 1, 1))),
                ('end_date', models.DateField(default=datetime.date(1970, 1, 2))),
                ('description', models.TextField(default='')),
                ('linked_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecv.CV')),
            ],
        ),
    ]
