# Generated by Django 2.2.12 on 2020-08-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecv', '0020_employment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('linked_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecv.CV')),
            ],
        ),
    ]
