# Generated by Django 2.2.12 on 2020-07-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_url',
            field=models.SlugField(default='default', unique=True),
        ),
    ]
